using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Bladehold.UI
{
    /// <summary>
    ///     View component for the scene transition loading screen (every scene load, including the one out of
    ///     the main menu): area art behind a dark lower band with an "Entering" eyebrow, the area name,
    ///     subtitle and lore blurb, and a progress bar with a status line and percentage.
    ///     The layout is generated by <c>ScreenRestyleBuilder.BuildLoadingScreen</c> (Bladehold > UI > Restyle >
    ///     Loading Screen); rebuild there rather than hand-editing the prefab.
    /// </summary>
    public class LoadingScreenUI : MonoBehaviour
    {
        [Header("Progress")]
        [Tooltip("Optional image fill (e.g. a logo) driven by progress.")]
        public Image logoLoadingFill;

        [Tooltip("Progress bar slider.")]
        public Slider loadingBar;

        [Tooltip("Status line under the bar (\"Loading\", \"Preparing shaders\"...).")]
        public TextMeshProUGUI loadingText;

        [Tooltip("Optional percentage label. When empty the percentage is appended to the status line.")]
        public TextMeshProUGUI percentText;

        [Tooltip("How fast the displayed progress catches up with the real one (fraction per second), so the bar glides instead of jumping.")]
        [SerializeField] private float progressCatchUpSpeed = 1.6f;

        [Header("Area Meta Information")]
        [Tooltip("Optional small line above the title (\"Entering\"). When set the title shows just the area name.")]
        public TextMeshProUGUI eyebrowText;

        [Tooltip("Area name (or \"Entering [DisplayName]\" when there's no eyebrow).")]
        public TextMeshProUGUI enteringTitleText;

        [Tooltip("Subtitle or region tagline (e.g. 'The Inner Gate').")]
        public TextMeshProUGUI subtitleText;

        [Tooltip("Lore blurb or objective description.")]
        public TextMeshProUGUI descriptionText;

        [Tooltip("Optional area artwork, shown over the default backdrop when the area has one.")]
        public Image previewImage;

        [Header("Backdrop")]
        [Tooltip("Optional art layer that slowly drifts (scales up) while the screen is visible.")]
        [SerializeField] private RectTransform backdropDrift;

        [Tooltip("Scale the backdrop drifts to over driftDuration seconds.")]
        [SerializeField] private float driftScale = 1.06f;

        [SerializeField] private float driftDuration = 8f;

        [Header("Transition")]
        [Tooltip("CanvasGroup used for smooth alpha fading.")]
        public CanvasGroup canvasGroup;

        private float targetProgress;
        private float shownProgress;
        private string statusOverride;
        private float visibleTime;

        private void Awake()
        {
            EnsureReferences();
        }

        public void EnsureReferences()
        {
            if (canvasGroup == null)
            {
                canvasGroup = GetComponent<CanvasGroup>();
            }

            if (loadingBar == null)
            {
                loadingBar = GetComponentInChildren<Slider>(true);
            }
        }

        private void Update()
        {
            visibleTime += Time.unscaledDeltaTime;
            if (backdropDrift != null && driftDuration > 0f)
            {
                float t = Mathf.Clamp01(visibleTime / driftDuration);
                float scale = Mathf.Lerp(1f, driftScale, 1f - (1f - t) * (1f - t));
                backdropDrift.localScale = new Vector3(scale, scale, 1f);
            }

            if (!Mathf.Approximately(shownProgress, targetProgress))
            {
                shownProgress = Mathf.MoveTowards(shownProgress, targetProgress, progressCatchUpSpeed * Time.unscaledDeltaTime);
                ApplyProgress();
            }
        }

        /// <summary>
        ///     Populates the loading screen with destination area metadata.
        /// </summary>
        public void SetAreaInfo(AreaMetadata meta)
        {
            if (meta == null) return;

            string areaName = !string.IsNullOrEmpty(meta.displayName) ? meta.displayName : Loc.Get("loading.unknown_area", "Unknown Realm");
            string entering = Loc.Get("loading.entering", "Entering");

            if (eyebrowText != null)
            {
                eyebrowText.text = entering;
            }
            if (enteringTitleText != null)
            {
                enteringTitleText.text = eyebrowText != null ? areaName : entering + " " + areaName;
            }

            if (subtitleText != null)
            {
                subtitleText.text = meta.subtitle ?? "";
                subtitleText.gameObject.SetActive(!string.IsNullOrEmpty(meta.subtitle));
            }

            if (descriptionText != null)
            {
                descriptionText.text = meta.description ?? "";
                descriptionText.gameObject.SetActive(!string.IsNullOrEmpty(meta.description));
            }

            if (previewImage != null)
            {
                previewImage.sprite = meta.previewSprite;
                previewImage.gameObject.SetActive(meta.previewSprite != null);
                // The layer covers the screen through an envelope fitter: match it to this art's shape.
                AspectRatioFitter fitter = previewImage.GetComponent<AspectRatioFitter>();
                if (fitter != null && meta.previewSprite != null)
                {
                    fitter.aspectRatio = meta.previewSprite.rect.width / meta.previewSprite.rect.height;
                }
            }
        }

        /// <summary>
        ///     Sets the loading progress (0..1). The bar and percentage glide towards it; <paramref name="customStatus" />
        ///     replaces the default "Loading" status line until the next call.
        /// </summary>
        public void SetProgress(float progress, string customStatus = null)
        {
            targetProgress = Mathf.Clamp01(progress);
            // Progress only moves forward on screen, except for the reset to 0 at the start of a load.
            if (targetProgress <= 0f)
            {
                shownProgress = 0f;
            }
            statusOverride = customStatus;
            ApplyProgress();
        }

        private void ApplyProgress()
        {
            if (logoLoadingFill != null)
            {
                logoLoadingFill.fillAmount = shownProgress;
            }

            if (loadingBar != null)
            {
                loadingBar.value = shownProgress;
            }

            string status = !string.IsNullOrEmpty(statusOverride) ? statusOverride : Loc.Get("loading.loading", "Loading");
            string percent = $"{shownProgress * 100f:F0}%";
            if (percentText != null)
            {
                percentText.text = percent;
                if (loadingText != null) loadingText.text = status;
            }
            else if (loadingText != null)
            {
                loadingText.text = $"{status}... {percent}";
            }
        }

        public IEnumerator FadeIn(float duration)
        {
            EnsureReferences();
            gameObject.SetActive(true);
            visibleTime = 0f;

            if (canvasGroup != null)
            {
                canvasGroup.blocksRaycasts = true;
                if (duration <= 0f)
                {
                    canvasGroup.alpha = 1f;
                    yield break;
                }

                float elapsed = 0f;
                float startAlpha = canvasGroup.alpha;
                while (elapsed < duration)
                {
                    elapsed += Time.unscaledDeltaTime;
                    canvasGroup.alpha = Mathf.Lerp(startAlpha, 1f, elapsed / duration);
                    yield return null;
                }
                canvasGroup.alpha = 1f;
            }
        }

        /// <summary>Lets the bar finish its glide to the current target (capped at <paramref name="maxWait" /> seconds).</summary>
        public IEnumerator WaitForProgressDisplay(float maxWait)
        {
            float waited = 0f;
            while (shownProgress < targetProgress && waited < maxWait)
            {
                waited += Time.unscaledDeltaTime;
                yield return null;
            }
            shownProgress = targetProgress;
            ApplyProgress();
        }

        public IEnumerator FadeOut(float duration)
        {
            EnsureReferences();

            if (canvasGroup != null)
            {
                if (duration <= 0f)
                {
                    canvasGroup.alpha = 0f;
                    canvasGroup.blocksRaycasts = false;
                    gameObject.SetActive(false);
                    yield break;
                }

                float elapsed = 0f;
                float startAlpha = canvasGroup.alpha;
                while (elapsed < duration)
                {
                    elapsed += Time.unscaledDeltaTime;
                    canvasGroup.alpha = Mathf.Lerp(startAlpha, 0f, elapsed / duration);
                    yield return null;
                }
                canvasGroup.alpha = 0f;
                canvasGroup.blocksRaycasts = false;
            }

            gameObject.SetActive(false);
        }
    }
}
