using UnityEngine;

/// <summary>
///     One node's miniature castle on the campaign map diorama. Generated by <c>CampaignDioramaBuilder</c>;
///     <see cref="CampaignDiorama" /> finds it by <see cref="NodeId" /> and pushes the node's status in, which
///     recolours the banners (horde red / liberated blue), greys out castles the route has left behind and
///     lights the pulsing ring under sectors that are open to deploy.
/// </summary>
public class CampaignDioramaSite : MonoBehaviour
{
    [SerializeField] private string nodeId;
    [Tooltip("World point the node's map label hangs from (the castle's front edge).")]
    [SerializeField] private Transform labelAnchor;
    [Tooltip("World point above the castle for the 'you are here' marker.")]
    [SerializeField] private Transform markerAnchor;
    [Tooltip("Castle and ground-dressing renderers that grey out with the node's status.")]
    [SerializeField] private Renderer[] bodyRenderers;
    [Tooltip("Banner cloth renderers, tinted by status.")]
    [SerializeField] private Renderer[] bannerRenderers;
    [Tooltip("Pulsing ground ring shown while the node is open to deploy.")]
    [SerializeField] private Renderer availableRing;
    [Tooltip("Banner sway in degrees.")]
    [SerializeField] private float bannerSwayDegrees = 9f;

    private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");
    private static readonly int GlowColorId = Shader.PropertyToID("_GlowColor");
    private static readonly int SaturationId = Shader.PropertyToID("_DioramaSaturation");
    private static readonly int BrightnessId = Shader.PropertyToID("_DioramaBrightness");

    private MaterialPropertyBlock block;
    private Quaternion[] bannerRestRotations;
    private float swayOffset;

    public string NodeId => nodeId;
    public Transform LabelAnchor => labelAnchor != null ? labelAnchor : transform;
    public Transform MarkerAnchor => markerAnchor != null ? markerAnchor : transform;

    private void Awake()
    {
        block = new MaterialPropertyBlock();
        swayOffset = Mathf.Abs(nodeId != null ? nodeId.GetHashCode() % 100 : 0) * 0.37f;
        if (bannerRenderers != null)
        {
            bannerRestRotations = new Quaternion[bannerRenderers.Length];
            for (int i = 0; i < bannerRenderers.Length; i++)
            {
                if (bannerRenderers[i] != null) bannerRestRotations[i] = bannerRenderers[i].transform.localRotation;
            }
        }
    }

    private void Start()
    {
        if (labelAnchor == null || markerAnchor == null)
        {
            Debug.LogError($"[CampaignDioramaSite] '{name}' ({nodeId}) is missing its label or marker anchor; rebuild the diorama.", this);
        }
    }

    private void Update()
    {
        if (bannerRenderers == null || bannerRestRotations == null) return;
        float t = Time.unscaledTime * 2.1f + swayOffset;
        for (int i = 0; i < bannerRenderers.Length; i++)
        {
            Renderer banner = bannerRenderers[i];
            if (banner == null) continue;
            float sway = (Mathf.Sin(t + i * 1.3f) + 0.4f * Mathf.Sin(t * 2.3f + i)) * bannerSwayDegrees;
            banner.transform.localRotation = bannerRestRotations[i] * Quaternion.Euler(0f, sway, 0f);
        }
    }

    public void ApplyStatus(CampaignNodeButtonUI.NodeVisualStatus status, CampaignDioramaLookSO look)
    {
        if (look == null) return;
        if (block == null) block = new MaterialPropertyBlock();

        float saturation = 1f;
        float brightness = 1f;
        Color banner = look.hordeBannerColor;
        switch (status)
        {
            case CampaignNodeButtonUI.NodeVisualStatus.Completed:
                saturation = look.completedSaturation;
                banner = look.liberatedBannerColor;
                break;
            case CampaignNodeButtonUI.NodeVisualStatus.Bypassed:
                saturation = look.bypassedSaturation;
                brightness = look.bypassedBrightness;
                break;
            case CampaignNodeButtonUI.NodeVisualStatus.DemoLocked:
                saturation = look.demoLockedSaturation;
                brightness = look.demoLockedBrightness;
                banner = look.demoLockedBannerColor;
                break;
        }

        if (bodyRenderers != null)
        {
            foreach (Renderer body in bodyRenderers)
            {
                if (body == null) continue;
                body.GetPropertyBlock(block);
                block.SetFloat(SaturationId, saturation);
                block.SetFloat(BrightnessId, brightness);
                body.SetPropertyBlock(block);
            }
        }

        if (bannerRenderers != null)
        {
            foreach (Renderer cloth in bannerRenderers)
            {
                if (cloth == null) continue;
                cloth.GetPropertyBlock(block);
                block.SetColor(BaseColorId, banner);
                block.SetFloat(SaturationId, status == CampaignNodeButtonUI.NodeVisualStatus.Bypassed ? saturation : 1f);
                block.SetFloat(BrightnessId, brightness);
                cloth.SetPropertyBlock(block);
            }
        }

        if (availableRing != null)
        {
            bool open = status == CampaignNodeButtonUI.NodeVisualStatus.Available;
            availableRing.gameObject.SetActive(open);
            if (open)
            {
                availableRing.GetPropertyBlock(block);
                block.SetColor(GlowColorId, look.availableRingColor);
                availableRing.SetPropertyBlock(block);
            }
        }
    }

#if UNITY_EDITOR
    /// <summary>Editor-only wiring for <c>CampaignDioramaBuilder</c>.</summary>
    public void EditorSetup(string id, Transform label, Transform marker, Renderer[] bodies, Renderer[] banners, Renderer ring)
    {
        nodeId = id;
        labelAnchor = label;
        markerAnchor = marker;
        bodyRenderers = bodies;
        bannerRenderers = banners;
        availableRing = ring;
    }
#endif
}
