using UnityEngine;

/// <summary>
///     One node's miniature castle on the campaign map diorama. Generated by <c>CampaignDioramaBuilder</c>;
///     <see cref="CampaignDiorama" /> finds it by <see cref="NodeId" /> and pushes the node's status in, which
///     recolours the banners (horde red / liberated blue), greys out castles the route has left behind and
///     lights the pulsing ring under sectors that are open to deploy.
/// </summary>
public class CampaignDioramaSite : MonoBehaviour
{
    [SerializeField] private string nodeId;
    [Tooltip("World point the node's map label hangs from (the castle's front edge).")]
    [SerializeField] private Transform labelAnchor;
    [Tooltip("World point above the castle for the 'you are here' marker.")]
    [SerializeField] private Transform markerAnchor;
    [Tooltip("Castle and ground-dressing renderers that grey out with the node's status.")]
    [SerializeField] private Renderer[] bodyRenderers;
    [Tooltip("Banner cloth renderers, tinted by status.")]
    [SerializeField] private Renderer[] bannerRenderers;
    [Tooltip("Pulsing ground ring shown while the node is open to deploy.")]
    [SerializeField] private Renderer availableRing;
    [Tooltip("Banner sway in degrees.")]
    [SerializeField] private float bannerSwayDegrees = 9f;

    private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");
    private static readonly int GlowColorId = Shader.PropertyToID("_GlowColor");
    private static readonly int SaturationId = Shader.PropertyToID("_DioramaSaturation");
    private static readonly int BrightnessId = Shader.PropertyToID("_DioramaBrightness");

    private static readonly int PulseSpeedId = Shader.PropertyToID("_PulseSpeed");
    private static readonly int ShapeId = Shader.PropertyToID("_Shape");
    private static readonly int DashLengthId = Shader.PropertyToID("_DashLength");
    private static readonly int DashFillId = Shader.PropertyToID("_DashFill");
    private static readonly int DashSpeedId = Shader.PropertyToID("_DashSpeed");

    private MaterialPropertyBlock block;
    private Quaternion[] bannerRestRotations;
    private float swayOffset;

    // Last status pushed in, so the inspect highlight can re-tint the castle on top of it.
    private CampaignNodeButtonUI.NodeVisualStatus status = CampaignNodeButtonUI.NodeVisualStatus.Locked;
    private CampaignDioramaLookSO lastLook;
    private bool inspected;
    // Built on first inspect from the open ring's renderer (same glow material), so no Editor wiring.
    private GameObject inspectHighlight;

    public string NodeId => nodeId;
    public Transform LabelAnchor => labelAnchor != null ? labelAnchor : transform;
    public Transform MarkerAnchor => markerAnchor != null ? markerAnchor : transform;

    private void Awake()
    {
        block = new MaterialPropertyBlock();
        swayOffset = Mathf.Abs(nodeId != null ? nodeId.GetHashCode() % 100 : 0) * 0.37f;
        if (bannerRenderers != null)
        {
            bannerRestRotations = new Quaternion[bannerRenderers.Length];
            for (int i = 0; i < bannerRenderers.Length; i++)
            {
                if (bannerRenderers[i] != null) bannerRestRotations[i] = bannerRenderers[i].transform.localRotation;
            }
        }
    }

    private void Start()
    {
        if (labelAnchor == null || markerAnchor == null)
        {
            Debug.LogError($"[CampaignDioramaSite] '{name}' ({nodeId}) is missing its label or marker anchor; rebuild the diorama.", this);
        }
    }

    private void Update()
    {
        if (bannerRenderers == null || bannerRestRotations == null) return;
        float t = Time.unscaledTime * 2.1f + swayOffset;
        for (int i = 0; i < bannerRenderers.Length; i++)
        {
            Renderer banner = bannerRenderers[i];
            if (banner == null) continue;
            float sway = (Mathf.Sin(t + i * 1.3f) + 0.4f * Mathf.Sin(t * 2.3f + i)) * bannerSwayDegrees;
            banner.transform.localRotation = bannerRestRotations[i] * Quaternion.Euler(0f, sway, 0f);
        }
    }

    public void ApplyStatus(CampaignNodeButtonUI.NodeVisualStatus newStatus, CampaignDioramaLookSO look)
    {
        if (look == null) return;
        status = newStatus;
        lastLook = look;
        ApplyTint(look);
    }

    /// <summary>
    ///     Marks this castle as the one the map is inspecting (its tooltip is up): a wide fast-pulsing ring,
    ///     a rising light column and a brighter castle, so the focus reads on the 3D map, not just the label.
    /// </summary>
    public void SetInspected(bool on, CampaignDioramaLookSO look)
    {
        if (look == null || inspected == on) return;
        inspected = on;
        lastLook = look;
        if (on) EnsureInspectHighlight(look);
        if (inspectHighlight != null) inspectHighlight.SetActive(on);
        ApplyTint(look);
    }

    private void EnsureInspectHighlight(CampaignDioramaLookSO look)
    {
        if (inspectHighlight != null || availableRing == null) return;
        Material glow = availableRing.sharedMaterial;
        if (glow == null) return;

        inspectHighlight = new GameObject("InspectHighlight");
        Transform root = inspectHighlight.transform;
        root.SetParent(availableRing.transform.parent, false);
        root.localPosition = availableRing.transform.localPosition;
        root.localRotation = Quaternion.identity;

        // Ring: a copy of the open ring's disc, scaled up so both show when the node is also open.
        GameObject ring = Instantiate(availableRing.gameObject, root);
        ring.name = "InspectRing";
        ring.SetActive(true);
        ring.transform.localPosition = Vector3.up * 0.01f;
        ring.transform.localRotation = availableRing.transform.localRotation;
        ring.transform.localScale = Vector3.Scale(availableRing.transform.localScale, new Vector3(look.inspectedRingScale, 1f, look.inspectedRingScale));
        Renderer ringRenderer = ring.GetComponent<Renderer>();
        ringRenderer.GetPropertyBlock(block);
        block.SetColor(GlowColorId, look.inspectedRingColor);
        block.SetFloat(PulseSpeedId, look.inspectedRingPulseSpeed);
        ringRenderer.SetPropertyBlock(block);

        // Beam: two crossed vertical quads using the shader's road shape as a solid-ish column of dashes rising up.
        // Ring radius in the castle's local units (from the mesh: the open ring may be inactive, with empty bounds).
        MeshFilter ringFilter = availableRing.GetComponent<MeshFilter>();
        float meshRadius = ringFilter != null && ringFilter.sharedMesh != null ? ringFilter.sharedMesh.bounds.extents.x : 1f;
        float radius = Mathf.Max(0.1f, meshRadius * availableRing.transform.localScale.x);
        float height = radius * look.inspectedBeamHeight;
        float width = radius * look.inspectedBeamWidth;
        Mesh beamMesh = BuildBeamMesh(width, height);
        for (int i = 0; i < 2; i++)
        {
            GameObject quad = new GameObject($"InspectBeam{i}", typeof(MeshFilter), typeof(MeshRenderer));
            quad.transform.SetParent(root, false);
            quad.transform.localRotation = Quaternion.Euler(0f, 45f + i * 90f, 0f);
            quad.GetComponent<MeshFilter>().sharedMesh = beamMesh;
            MeshRenderer beam = quad.GetComponent<MeshRenderer>();
            beam.sharedMaterial = glow;
            beam.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            beam.receiveShadows = false;
            block.Clear();
            block.SetFloat(ShapeId, 0f);
            block.SetColor(GlowColorId, look.inspectedBeamColor);
            block.SetFloat(DashLengthId, height * 0.18f);
            block.SetFloat(DashFillId, 0.7f);
            block.SetFloat(DashSpeedId, 0.8f);
            beam.SetPropertyBlock(block);
        }
        block.Clear();
    }

    /// <summary>A vertical quad: uv.x runs up the beam in world-ish units (the dash axis), uv.y across it.</summary>
    private static Mesh BuildBeamMesh(float width, float height)
    {
        float h = width * 0.5f;
        Mesh mesh = new Mesh { name = "DioramaInspectBeam" };
        mesh.vertices = new[] { new Vector3(-h, 0f, 0f), new Vector3(h, 0f, 0f), new Vector3(-h, height, 0f), new Vector3(h, height, 0f) };
        mesh.uv = new[] { new Vector2(0f, 0f), new Vector2(0f, 1f), new Vector2(height, 0f), new Vector2(height, 1f) };
        mesh.triangles = new[] { 0, 2, 1, 1, 2, 3 };
        mesh.RecalculateBounds();
        return mesh;
    }

    private void ApplyTint(CampaignDioramaLookSO look)
    {
        if (block == null) block = new MaterialPropertyBlock();

        float saturation = 1f;
        float brightness = 1f;
        Color banner = look.hordeBannerColor;
        switch (status)
        {
            case CampaignNodeButtonUI.NodeVisualStatus.Completed:
                saturation = look.completedSaturation;
                banner = look.liberatedBannerColor;
                break;
            case CampaignNodeButtonUI.NodeVisualStatus.Bypassed:
                saturation = look.bypassedSaturation;
                brightness = look.bypassedBrightness;
                break;
            case CampaignNodeButtonUI.NodeVisualStatus.DemoLocked:
                saturation = look.demoLockedSaturation;
                brightness = look.demoLockedBrightness;
                banner = look.demoLockedBannerColor;
                break;
        }
        if (inspected) brightness *= look.inspectedBrightness;

        if (bodyRenderers != null)
        {
            foreach (Renderer body in bodyRenderers)
            {
                if (body == null) continue;
                body.GetPropertyBlock(block);
                block.SetFloat(SaturationId, saturation);
                block.SetFloat(BrightnessId, brightness);
                body.SetPropertyBlock(block);
            }
        }

        if (bannerRenderers != null)
        {
            foreach (Renderer cloth in bannerRenderers)
            {
                if (cloth == null) continue;
                cloth.GetPropertyBlock(block);
                block.SetColor(BaseColorId, banner);
                block.SetFloat(SaturationId, status == CampaignNodeButtonUI.NodeVisualStatus.Bypassed ? saturation : 1f);
                block.SetFloat(BrightnessId, brightness);
                cloth.SetPropertyBlock(block);
            }
        }

        if (availableRing != null)
        {
            bool open = status == CampaignNodeButtonUI.NodeVisualStatus.Available;
            availableRing.gameObject.SetActive(open);
            if (open)
            {
                availableRing.GetPropertyBlock(block);
                block.SetColor(GlowColorId, look.availableRingColor);
                availableRing.SetPropertyBlock(block);
            }
        }
    }

#if UNITY_EDITOR
    /// <summary>Editor-only wiring for <c>CampaignDioramaBuilder</c>.</summary>
    public void EditorSetup(string id, Transform label, Transform marker, Renderer[] bodies, Renderer[] banners, Renderer ring)
    {
        nodeId = id;
        labelAnchor = label;
        markerAnchor = marker;
        bodyRenderers = bodies;
        bannerRenderers = banners;
        availableRing = ring;
    }
#endif
}
