using System.Collections.Generic;
using UnityEngine;

/// <summary>
///     The 3D campaign map: a baked miniature landscape with one castle per node (<see cref="CampaignDioramaSite" />)
///     and a route overlay per edge (<see cref="CampaignDioramaRoad" />). Generated by
///     <c>Bladehold > Campaign > Build Map Diorama</c>; never hand-edit the hierarchy. <see cref="CampaignMapUI" />
///     owns the campaign logic and calls in here to show status, project label positions and pan the camera.
/// </summary>
public class CampaignDiorama : MonoBehaviour
{
    [SerializeField] private CampaignDioramaLookSO look;
    [SerializeField] private CampaignDioramaCamera dioramaCamera;
    [SerializeField] private CampaignDioramaSite[] sites;
    [SerializeField] private CampaignDioramaRoad[] roads;
    [Tooltip("World position of map coordinate (0, 0).")]
    [SerializeField] private Vector3 mapOrigin;
    [Tooltip("World units per map unit (CampaignNodeSO.mapPosition).")]
    [SerializeField] private float worldPerMapUnit = 1f / 32f;

    private readonly Dictionary<string, CampaignDioramaSite> siteById = new Dictionary<string, CampaignDioramaSite>(System.StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, CampaignDioramaRoad> roadByEdge = new Dictionary<string, CampaignDioramaRoad>(System.StringComparer.OrdinalIgnoreCase);
    // NonSerialized: a domain reload would otherwise keep the flag but drop the dictionaries,
    // leaving every lookup empty (labels stop following their castles).
    [System.NonSerialized] private bool indexed;

    public CampaignDioramaCamera DioramaCamera => dioramaCamera;
    public Camera Camera => dioramaCamera != null ? dioramaCamera.Camera : null;
    public bool IsValid => look != null && dioramaCamera != null && sites != null && sites.Length > 0;

    private void Awake()
    {
        BuildIndex();
    }

    private void BuildIndex()
    {
        if (indexed) return;
        indexed = true;
        if (sites != null)
        {
            foreach (CampaignDioramaSite site in sites)
            {
                if (site != null && !string.IsNullOrEmpty(site.NodeId)) siteById[site.NodeId] = site;
            }
        }
        if (roads != null)
        {
            foreach (CampaignDioramaRoad road in roads)
            {
                if (road != null) roadByEdge[EdgeKey(road.FromNodeId, road.ToNodeId)] = road;
            }
        }
    }

    private static string EdgeKey(string from, string to) => from + ">" + to;

    public bool TryGetSite(string nodeId, out CampaignDioramaSite site)
    {
        BuildIndex();
        site = null;
        return !string.IsNullOrEmpty(nodeId) && siteById.TryGetValue(nodeId, out site) && site != null;
    }

    public void ApplyNodeStatus(string nodeId, CampaignNodeButtonUI.NodeVisualStatus status)
    {
        if (TryGetSite(nodeId, out CampaignDioramaSite site)) site.ApplyStatus(status, look);
    }

    /// <summary>Turns the 3D "inspecting this node" highlight on or off for one castle.</summary>
    public void SetInspected(string nodeId, bool inspected)
    {
        if (TryGetSite(nodeId, out CampaignDioramaSite site)) site.SetInspected(inspected, look);
    }

    public void ApplyRoadStatus(string fromNodeId, string toNodeId, CampaignDioramaRoad.RoadStatus status)
    {
        BuildIndex();
        if (roadByEdge.TryGetValue(EdgeKey(fromNodeId, toNodeId), out CampaignDioramaRoad road) && road != null)
        {
            road.ApplyStatus(status, look);
        }
    }

    /// <summary>World X of a map-space X coordinate (tier columns, node positions).</summary>
    public float MapToWorldX(float mapX) => mapOrigin.x + mapX * worldPerMapUnit;

    /// <summary>Screen position of a world point, and whether it is in front of the camera.</summary>
    public bool WorldToScreen(Vector3 world, out Vector2 screen)
    {
        Camera cam = Camera;
        if (cam == null)
        {
            screen = Vector2.zero;
            return false;
        }
        Vector3 p = cam.WorldToScreenPoint(world);
        screen = new Vector2(p.x, p.y);
        return p.z > 0f;
    }

    public void FocusOnNode(string nodeId, bool instant = false)
    {
        if (dioramaCamera != null && TryGetSite(nodeId, out CampaignDioramaSite site))
        {
            dioramaCamera.FocusOn(site.transform.position.x, instant);
        }
    }

#if UNITY_EDITOR
    /// <summary>Editor-only wiring for <c>CampaignDioramaBuilder</c>.</summary>
    public void EditorSetup(CampaignDioramaLookSO lookAsset, CampaignDioramaCamera cameraRig, CampaignDioramaSite[] builtSites,
        CampaignDioramaRoad[] builtRoads, Vector3 origin, float scale)
    {
        look = lookAsset;
        dioramaCamera = cameraRig;
        sites = builtSites;
        roads = builtRoads;
        mapOrigin = origin;
        worldPerMapUnit = scale;
        indexed = false;
        siteById.Clear();
        roadByEdge.Clear();
    }
#endif
}
